{{- if .Values.httpRoute.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pms-chart.fullname" . }}
  labels: {{ include "pms-chart.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames: {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "pms-chart.fullname" . }}
          port: {{ .Values.service.port }}
{{- end -}}
